from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

import time

url = 'https://pzz.by/pizzas'
driver = webdriver.Safari()
driver.maximize_window()
actions = ActionChains(driver)

driver.get(url=url)
element = driver.find_element(By.ID, 'pizza-5')
time.sleep(2)
driver.execute_script("arguments[0].scrollIntoView();", element)
time.sleep(3)
driver.find_element(By.XPATH, '//*[@id="mainDiv"]/div[1]/ul[2]/li[19]/div[5]/div').click()
time.sleep(3)
print('button_test')
ips = driver.find_element(By.CLASS_NAME, 'select2-choice')
ips.click()
time.sleep(3)
ips.send_keys('Партизанский просп')
time.sleep(3)
ips.send_keys(Keys.ENTER)
time.sleep(3)
ips2 = driver.find_element(By.XPATH, '//*[@id="s2id_home-number-modal"]')
ips2.click()
time.sleep(3)
ips2.send_keys('34/1')
time.sleep(3)
ips2.send_keys(Keys.ENTER)
time.sleep(3)
btn = driver.find_element(By.XPATH, '//*[@id="byaddress"]')
btn.click()
time.sleep(5)
driver.get('https://pzz.by/cart')
driver.find_element(By.XPATH, '//*[@id="cartContent"]/div[4]/ul/li[5]/div[3]/div/button').click()
time.sleep(3)
driver.find_element(By.XPATH, '//*[@id="cartContent"]/div[8]/ul/li[2]/div[3]/div/button').click()
time.sleep(5)
header = driver.find_element(By.XPATH, '/html/body/div[2]')
driver.execute_script("arguments[0].scrollIntoView();", header)
time.sleep(10)
username = driver.find_element(By.XPATH, '//*[@id="address_form"]/form/div[1]/input')
username.send_keys('Роман')
time.sleep(3)
mobile = driver.find_element(By.XPATH, '//*[@id="address_form"]/form/div[2]/input[2]')
mobile.send_keys('291424993')
time.sleep(3)
flat = driver.find_element(By.XPATH, '//*[@id="address_form"]/form/div[3]/div[3]/input')
flat.send_keys('89')
time.sleep(3)
entrance = driver.find_element(By.XPATH, '//*[@id="address_form"]/form/div[3]/div[4]/input')
entrance.send_keys('1')
time.sleep(3)
floor = driver.find_element(By.XPATH, '//*[@id="address_form"]/form/div[3]/div[5]/input')
floor.send_keys('14')
time.sleep(3)
intercom = driver.find_element(By.XPATH, '//*[@id="address_form"]/form/div[3]/div[6]/input')
intercom.send_keys('+')
time.sleep(3)
comment = driver.find_element(By.XPATH, '//*[@id="cartComment"]')
comment.send_keys('Пиццу без болгарского перца пожалуйста. Хорошего дня.')
time.sleep(3)
radio1 = driver.find_element(By.XPATH, '//*[@id="address_form"]/form/div[12]/div[2]/label')
radio1.click()
time.sleep(3)
radio2 = driver.find_element(By.XPATH, '//*[@id="runtimeDeliveryButton"]')
radio2.click()
time.sleep(5)
finish_btn = driver.find_element(By.XPATH, '//*[@id="address_form"]/div/div[2]/span')
finish_btn.click()
time.sleep(15)
print('ending')
driver.quit()
